# Generated by Django 3.0.7 on 2020-06-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200624_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
