# Generated by Django 3.0.7 on 2020-06-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_education_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cv.Skill')),
            ],
        ),
    ]
