# Generated by Django 3.0.7 on 2020-08-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_portfolio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Framework')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Portfolio')),
            ],
        ),
    ]
