# Generated by Django 3.0.7 on 2020-08-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='show_skill',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
