# Generated by Django 3.0.7 on 2020-09-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_framework_show_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
